<Project Sdk="Aspire.AppHost.Sdk/13.2.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>58f1fba2-cc40-4730-ad9d-ef0fde0633dd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.2.1" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartInventory.API\SmartInventory.API.csproj" />
  </ItemGroup>

</Project>
