// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInventory.Infrastructure.Data.Context;

#nullable disable

namespace SmartInventory.Infrastructure.Migrations.Inventory
{
    [DbContext(typeof(SmartInventoryDbContext))]
    partial class SmartInventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartInventory.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumStockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ReorderPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ReorderQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Products_Category");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Category"), new[] { "Name", "IsActive" });

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Products_IsActive");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IsActive"), new[] { "SKU", "Name" });

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasDatabaseName("UK_Products_SKU");

                    b.ToTable("Products", "Inventory", t =>
                        {
                            t.HasCheckConstraint("CK_Products_MinimumStockLevel", "[MinimumStockLevel] >= 0");

                            t.HasCheckConstraint("CK_Products_ReorderPoint", "[ReorderPoint] >= 0");

                            t.HasCheckConstraint("CK_Products_ReorderQuantity", "[ReorderQuantity] > 0");

                            t.HasCheckConstraint("CK_Products_UnitCost", "[UnitCost] IS NULL OR [UnitCost] >= 0");
                        });
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ShippingCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate")
                        .IsDescending()
                        .HasDatabaseName("IX_PurchaseOrders_OrderDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("OrderDate"), new[] { "OrderNumber", "Status", "TotalAmount" });

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UK_PurchaseOrders_Number");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PurchaseOrders_Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status"), new[] { "OrderNumber", "OrderDate", "SupplierId" });

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("IX_PurchaseOrders_SupplierId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SupplierId"), new[] { "OrderDate", "Status", "TotalAmount" });

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_PurchaseOrders_WarehouseId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("WarehouseId"), new[] { "OrderDate", "Status" });

                    b.ToTable("PurchaseOrders", "Purchasing", t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrders_ExpectedDate", "[ExpectedDeliveryDate] >= [OrderDate]");

                            t.HasCheckConstraint("CK_PurchaseOrders_ShippingCost", "[ShippingCost] >= 0");

                            t.HasCheckConstraint("CK_PurchaseOrders_SubTotal", "[SubTotal] >= 0");

                            t.HasCheckConstraint("CK_PurchaseOrders_TaxAmount", "[TaxAmount] >= 0");

                            t.HasCheckConstraint("CK_PurchaseOrders_TotalAmount", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReceivedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_PurchaseOrderItems_ProductId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProductId"), new[] { "PurchaseOrderId", "Quantity", "UnitCost" });

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("IX_PurchaseOrderItems_PurchaseOrderId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PurchaseOrderId"), new[] { "ProductId", "Quantity", "UnitCost" });

                    b.HasIndex("PurchaseOrderId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UK_PurchaseOrderItems_PO_Product");

                    b.ToTable("PurchaseOrderItems", "Purchasing", t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrderItems_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_PurchaseOrderItems_ReceivedQuantity", "[ReceivedQuantity] >= 0 AND [ReceivedQuantity] <= [Quantity]");

                            t.HasCheckConstraint("CK_PurchaseOrderItems_UnitCost", "[UnitCost] >= 0");
                        });
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("LastStockTakeDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityAvailable")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,4)")
                        .HasComputedColumnSql("[QuantityOnHand] - [QuantityReserved]", true);

                    b.Property<decimal>("QuantityOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("QuantityReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Stock_ProductId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProductId"), new[] { "WarehouseId", "QuantityOnHand", "QuantityAvailable" });

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_Stock_WarehouseId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("WarehouseId"), new[] { "ProductId", "QuantityOnHand", "QuantityAvailable" });

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("UK_Stock_Product_Warehouse");

                    b.ToTable("Stock", "Inventory", t =>
                        {
                            t.HasCheckConstraint("CK_Stock_QuantityOnHand", "[QuantityOnHand] >= 0");

                            t.HasCheckConstraint("CK_Stock_QuantityReserved", "[QuantityReserved] >= 0");

                            t.HasCheckConstraint("CK_Stock_Reserved_LTE_OnHand", "[QuantityReserved] <= [QuantityOnHand]");
                        });
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.StockAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AlertType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolutionNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("ThresholdQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_StockAlerts_CreatedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedAt"), new[] { "Status", "Severity", "ProductId" });

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_StockAlerts_ProductId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProductId"), new[] { "Status", "Severity", "CreatedAt" });

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_StockAlerts_Severity");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Severity"), new[] { "Status", "ProductId", "CreatedAt" });

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_StockAlerts_Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status"), new[] { "ProductId", "WarehouseId", "Severity", "CreatedAt" });

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_StockAlerts_WarehouseId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("WarehouseId"), new[] { "Status", "Severity", "CreatedAt" });

                    b.ToTable("StockAlerts", "Alerts");
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("DestinationWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReversed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ReversedByTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWarehouseId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_StockTransactions_ProductId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProductId"), new[] { "TransactionDate", "Quantity", "TransactionType" });

                    b.HasIndex("ReferenceNumber")
                        .HasDatabaseName("IX_StockTransactions_Reference")
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.HasIndex("ReversedByTransactionId");

                    b.HasIndex("SourceWarehouseId");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("IX_StockTransactions_Date");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TransactionDate"), new[] { "ProductId", "WarehouseId", "Quantity", "TransactionType" });

                    b.HasIndex("TransactionNumber")
                        .IsUnique()
                        .HasDatabaseName("UK_StockTransactions_Number");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("IX_StockTransactions_Type");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TransactionType"), new[] { "ProductId", "WarehouseId", "TransactionDate" });

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("IX_StockTransactions_WarehouseId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("WarehouseId"), new[] { "TransactionDate", "ProductId", "Quantity" });

                    b.ToTable("StockTransactions", "Inventory", t =>
                        {
                            t.HasCheckConstraint("CK_StockTransactions_Quantity", "[Quantity] <> 0");

                            t.HasCheckConstraint("CK_StockTransactions_TransactionDate", "[TransactionDate] <= SYSUTCDATETIME()");

                            t.HasCheckConstraint("CK_StockTransactions_UnitCost", "[UnitCost] IS NULL OR [UnitCost] >= 0");
                        });
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LeadTimeDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("MinimumOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(3.0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UK_Suppliers_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Suppliers_IsActive");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IsActive"), new[] { "Code", "Name" });

                    b.HasIndex("Rating")
                        .IsDescending()
                        .HasDatabaseName("IX_Suppliers_Rating");

                    b.ToTable("Suppliers", "Purchasing", t =>
                        {
                            t.HasCheckConstraint("CK_Suppliers_Email", "[Email] IS NULL OR [Email] LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Suppliers_LeadTimeDays", "[LeadTimeDays] >= 0");

                            t.HasCheckConstraint("CK_Suppliers_MinimumOrderValue", "[MinimumOrderValue] IS NULL OR [MinimumOrderValue] >= 0");

                            t.HasCheckConstraint("CK_Suppliers_Rating", "[Rating] >= 1.0 AND [Rating] <= 5.0");
                        });
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("WarehouseType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UK_Warehouses_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Warehouses_IsActive");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IsActive"), new[] { "Code", "Name" });

                    b.HasIndex("WarehouseType")
                        .HasDatabaseName("IX_Warehouses_Type");

                    b.ToTable("Warehouses", "Inventory", t =>
                        {
                            t.HasCheckConstraint("CK_Warehouses_Capacity", "[Capacity] IS NULL OR [Capacity] > 0");

                            t.HasCheckConstraint("CK_Warehouses_Email", "[ManagerEmail] IS NULL OR [ManagerEmail] LIKE '%_@__%.__%'");
                        });
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("SmartInventory.Domain.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrders_Suppliers");

                    b.HasOne("SmartInventory.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrders_Warehouses");
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("SmartInventory.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrderItems_Products");

                    b.HasOne("SmartInventory.Domain.Entities.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrderItems_PurchaseOrders");
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.Stock", b =>
                {
                    b.HasOne("SmartInventory.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Stock_Products");

                    b.HasOne("SmartInventory.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Stock_Warehouses");
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.StockAlert", b =>
                {
                    b.HasOne("SmartInventory.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockAlerts_Products");

                    b.HasOne("SmartInventory.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockAlerts_Warehouses");
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.StockTransaction", b =>
                {
                    b.HasOne("SmartInventory.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_StockTransactions_DestinationWarehouse");

                    b.HasOne("SmartInventory.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockTransactions_Products");

                    b.HasOne("SmartInventory.Domain.Entities.StockTransaction", null)
                        .WithMany()
                        .HasForeignKey("ReversedByTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_StockTransactions_ReversedBy");

                    b.HasOne("SmartInventory.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_StockTransactions_SourceWarehouse");

                    b.HasOne("SmartInventory.Domain.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StockTransactions_Warehouses");
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.Supplier", b =>
                {
                    b.OwnsOne("SmartInventory.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_Street");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers", "Purchasing");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.Warehouse", b =>
                {
                    b.OwnsOne("SmartInventory.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_Street");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses", "Inventory");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SmartInventory.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
